name: Test

on:
- push
- pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node_version: [ 8.x, 10.x , 12.x ]
        include:
        - node_version: 8.x
          run_lint_tests: "True"

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        set -e;

        npm install -g gulp;
        npm install;

    - name: Run lint tests
      if: ${{ matrix.run_lint_tests }}
      run: |
        TEST_SUITE="lint" test/test.sh
    
    - name: Run tests
      run: |
        TEST_SUITE="unit" test/test.sh ;

        #
        # gulp send-stats-to-coveralls ;
